#include "VulkanErrors.h"

#include <stdexcept>

namespace {
#define STRING_CASE(x) \
  case x:              \
    return #x

const char* VkResultToString(VkResult r) {
  switch (r) {
    // Success / info codes
    STRING_CASE(VK_SUCCESS);
    STRING_CASE(VK_NOT_READY);
    STRING_CASE(VK_TIMEOUT);
    STRING_CASE(VK_EVENT_SET);
    STRING_CASE(VK_EVENT_RESET);
    STRING_CASE(VK_INCOMPLETE);
    STRING_CASE(VK_SUBOPTIMAL_KHR);
    STRING_CASE(VK_THREAD_IDLE_KHR);
    STRING_CASE(VK_THREAD_DONE_KHR);
    STRING_CASE(VK_OPERATION_DEFERRED_KHR);
    STRING_CASE(VK_OPERATION_NOT_DEFERRED_KHR);
    STRING_CASE(VK_PIPELINE_COMPILE_REQUIRED);
    STRING_CASE(VK_INCOMPATIBLE_SHADER_BINARY_EXT);
    // Core errors
    STRING_CASE(VK_ERROR_OUT_OF_HOST_MEMORY);
    STRING_CASE(VK_ERROR_OUT_OF_DEVICE_MEMORY);
    STRING_CASE(VK_ERROR_INITIALIZATION_FAILED);
    STRING_CASE(VK_ERROR_DEVICE_LOST);
    STRING_CASE(VK_ERROR_MEMORY_MAP_FAILED);
    STRING_CASE(VK_ERROR_LAYER_NOT_PRESENT);
    STRING_CASE(VK_ERROR_EXTENSION_NOT_PRESENT);
    STRING_CASE(VK_ERROR_FEATURE_NOT_PRESENT);
    STRING_CASE(VK_ERROR_INCOMPATIBLE_DRIVER);
    STRING_CASE(VK_ERROR_TOO_MANY_OBJECTS);
    STRING_CASE(VK_ERROR_FORMAT_NOT_SUPPORTED);
    STRING_CASE(VK_ERROR_FRAGMENTED_POOL);
    STRING_CASE(VK_ERROR_UNKNOWN);
    STRING_CASE(VK_ERROR_OUT_OF_POOL_MEMORY);
    STRING_CASE(VK_ERROR_INVALID_EXTERNAL_HANDLE);
    STRING_CASE(VK_ERROR_FRAGMENTATION);
    STRING_CASE(VK_ERROR_INVALID_OPAQUE_CAPTURE_ADDRESS);
    STRING_CASE(VK_ERROR_NOT_PERMITTED);
    // Extension errors
    STRING_CASE(VK_ERROR_SURFACE_LOST_KHR);
    STRING_CASE(VK_ERROR_NATIVE_WINDOW_IN_USE_KHR);
    STRING_CASE(VK_ERROR_OUT_OF_DATE_KHR);
    STRING_CASE(VK_ERROR_INCOMPATIBLE_DISPLAY_KHR);
    STRING_CASE(VK_ERROR_VALIDATION_FAILED_EXT);
    STRING_CASE(VK_ERROR_INVALID_SHADER_NV);
    STRING_CASE(VK_ERROR_IMAGE_USAGE_NOT_SUPPORTED_KHR);
    STRING_CASE(VK_ERROR_VIDEO_PICTURE_LAYOUT_NOT_SUPPORTED_KHR);
    STRING_CASE(VK_ERROR_VIDEO_PROFILE_OPERATION_NOT_SUPPORTED_KHR);
    STRING_CASE(VK_ERROR_VIDEO_PROFILE_FORMAT_NOT_SUPPORTED_KHR);
    STRING_CASE(VK_ERROR_VIDEO_PROFILE_CODEC_NOT_SUPPORTED_KHR);
    STRING_CASE(VK_ERROR_VIDEO_STD_VERSION_NOT_SUPPORTED_KHR);
    STRING_CASE(VK_ERROR_INVALID_DRM_FORMAT_MODIFIER_PLANE_LAYOUT_EXT);
    STRING_CASE(VK_ERROR_FULL_SCREEN_EXCLUSIVE_MODE_LOST_EXT);
    STRING_CASE(VK_ERROR_INVALID_VIDEO_STD_PARAMETERS_KHR);
    STRING_CASE(VK_ERROR_COMPRESSION_EXHAUSTED_EXT);
    STRING_CASE(VK_ERROR_NOT_ENOUGH_SPACE_KHR);
    default:
      return "VK_UNKNOWN_ERROR";
  }
}
#undef STRING_CASE

}  // namespace

void VkCheck(VkResult result, const char* file, int line) {
  if (result != VK_SUCCESS) {
    throw std::runtime_error(std::string("Vulkan error at ") + file + ":" +
                             std::to_string(line) + " => " +
                             VkResultToString(result) + " (" +
                             std::to_string(static_cast<int>(result)) + ")");
  }
}
